const escape=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const json=value=>JSON.stringify(value).replace(/</g,'\\u003c');
export function renderPage(html,products,assetVersion='local'){
  html=html.replace(/(href|src)="(\/(?:css|js)\/[a-zA-Z0-9_-]+\.(?:css|js))"/g,(_,attribute,url)=>`${attribute}="${url}?v=${assetVersion}"`);
  const catalog={"@context":"https://schema.org","@type":"ItemList",itemListElement:products.map((p,index)=>({"@type":"ListItem",position:index+1,item:{"@type":"Product",name:p.name,description:p.description,image:p.image.startsWith('/')?'https://deluxegames.vercel.app'+p.image:p.image,offers:{"@type":"Offer",priceCurrency:'ARS',price:p.price,...(p.preorder?{availability:'https://schema.org/PreOrder'}:p.stock===null?{}:{availability:p.stock===0?'https://schema.org/OutOfStock':'https://schema.org/InStock'})}}}))};
  const faq=[...html.matchAll(/<details><summary>(.*?)<\/summary><p>(.*?)<\/p><\/details>/g)].map(m=>({'@type':'Question',name:m[1],acceptedAnswer:{'@type':'Answer',text:m[2]}}));
  const structured=`<script type="application/ld+json">${json(catalog)}</script><script type="application/ld+json">${json({'@context':'https://schema.org','@type':'FAQPage',mainEntity:faq})}</script>`;
  const cards=products.map(p=>`<article class="product-card" data-id="${escape(p.id)}"><div class="card-visual"><button class="card-image-button" data-detail="${escape(p.id)}" aria-label="Ver detalles de ${escape(p.name)}"><img src="${escape(p.image)}" alt="${escape(p.name)}" width="600" height="771" loading="lazy" decoding="async"></button></div><div class="card-meta">${escape(p.platforms.join(' / '))} · DIGITAL</div><h3 class="card-title">${escape(p.name)}</h3><p class="card-format">${escape(p.type)}</p><div class="card-price">$${p.price.toLocaleString('es-AR')} <small>ARS</small></div><p class="card-note">${p.preorder?'Preventa · Fecha y condiciones a confirmar':'Disponibilidad a confirmar'}</p></article>`).join('');
  return html.replace('</head>',structured+'</head>').replace('<div class="loading-state">Preparando tu próxima partida…</div>',cards+'<noscript><p>Activá JavaScript para usar el carrito y tu cuenta. Podés consultar por WhatsApp desde el pie de página.</p></noscript>');
}
